# Generated by Django 5.0.4 on 2024-04-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('road', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('postcode', models.CharField(max_length=20)),
            ],
        ),
    ]
