# Generated by Django 5.0.4 on 2024-04-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='Location',
        ),
    ]
